export type SubTypes = SystemSubTypes | LoginSubTypes | GuardSubTypes | DeviceSubTypes | EMSSubTypes | InfoSubTypes | HealthcareSubTypes | SettingSubTypes | ElevatorCallSubTypes | EtceteraSubTypes | ApplicationLogSubTypes;

export enum Types {
    
    SYSTEM = 0,
    LOGIN = 1,
    GUARD = 2,
    DEVICE = 3,
    EMS = 4,
    INFO = 5,
    HEALTHCARE = 6,
    SETTING = 7,
    ELEVATOR_CALL = 8,
    ETCETERA = 9,
    APPLICATION_LOG = 100
    
}

export enum Errors {

    SUCCESS = 0,
    UNEXPECTED_BEHAVIOR = 1,
    UNCERTIFIED_DEVICE = 2,
    INVALID_LOGIN_PIN = 3,
    INVALID_USERNAME_AND_PASSWORD = 4,
    UNKNOWN_PHONE_NUMBER = 5,
    TRY_AGAIN_LAYER = 6,
    UNSTABLE_WALL_PAD_COMMUNICATION = 7,
    UNSTABLE_COMPLEX_MMF_SERVER_COMMUNICATION = 8,
    UNSTABLE_DEVICE_COMMUNICATION = 9,
    UNSTABLE_DEVICE_CONTROL_COMMUNICATION = 10,
    INVALID_PARAMETER = 11,
    DENIED_DEVICE_TYPE = 12,
    TOO_MANY_REQUESTS = 13,
    NO_RESPONSE_CCTV = 14,
    NO_CCTV = 15,
    CCTV_ERROR = 16,
    LOGGED_OUT_TIMEOUT = 17,
    UNSTABLE_COMPLEX_MMF_SERVER_COMMUNICATION2 = 18,
    UNSTABLE_REMOTE_DIALOGUE_SERVER_COMMUNICATION = 181,
    USERNAME_EXISTS = 19,
    INCORRECT_INFO = 20,
    INCORRECT_INFO2 = 21,
    INVALID_CERTIFICATION_NUMBER = 22,
    TIMEOUT_CERTIFICATION_NUMBER = 23,
    DETAILED_ADDRESS_NOT_FOUND = 24,
    REGISTRATION_NOT_COMPLETED = 25,
    UNEXPECTED_BEHAVIOR_WHILE_CERTIFYING = 26,
    HEAD_OF_HOUSEHOLD_EXISTS = 27,
    EMAIL_ADDRESS_EXISTS = 28,
    INVALID_PASSWORD = 29,
    UNSTABLE_CAR_REGISTRATION = 30,
    UNSTABLE_CAR_REMOVAL = 31,
    WALL_PAD_CERTIFICATION_REQUIRED = 32,
    OUTING_MODE_ALREADY_TURNED_ON = 33,
    UNEXPECTED_BEHAVIOR_WHILE_ACTIVATING_OUTING_MODE = 34,
    MAXIMUM_CAR_REGISTRATION_EXCEEDS = 35,
    INVALID_APARTMENT_PASSWORD = 36,
    INVALID_EMAIL_ADDRESS = 37,
    SETTING_IDENTICAL = 38,
    UNEXPECTED_BEHAVIOR_WHILE_CERTIFYING2 = 39,
    AT_HOME_MODE_ALREADY_TURNED_ON = 40,
    OUT_OF_SERVICE_AREA = 41,
    REGULAR_CAR_EXISTS = 42
    
}

export enum SystemSubTypes {

    GENERAL = 0,
    CONNECTED = 1,
    CLOSED = 2,
    RESERVED = 3,
    CONNECTION_STATUS = 4,
    LOGIN_STATUS = 5,
    APPLICATION_INFO = 6,
    OPEN = 7,
    OPEN_RESPONSE = 8,
    TIMED_OUT = 9,
    CLEAR_CACHE = 10
    
}

export enum LoginSubTypes {
    
    COMPLEX_LIST_REQUEST = 1,
    COMPLEX_LIST_RESPONSE = 2,
    COMPLEX_INFO_REQUEST = 3,
    COMPLEX_INFO_RESPONSE = 4,
    CERTIFICATION_PIN_REQUEST = 5,
    CERTIFICATION_PIN_RESPONSE = 6,
    MENU_REQUEST = 7,
    MENU_RESPONSE = 8,
    LOGIN_PIN_REQUEST = 9,
    LOGIN_PIN_RESPONSE = 10,
    COMMON_INFO_REQUEST = 11,
    COMMON_INFO_RESPONSE = 12,
    PUSH_REQUEST = 13,
    PUSH_RESPONSE = 14,
    ALIVE_REQUEST = 15,
    ALIVE_RESPONSE = 16,
    DELETE_CERTIFICATION_REQUEST = 17,
    DELETE_CERTIFICATION_RESPONSE = 18,
    REGISTER_REQUEST = 19,
    REGISTER_RESPONSE = 20,
    CHECK_ID_REQUEST = 21,
    CHECK_ID_RESPONSE = 22,
    CHECK_HEAD_OF_HOUSEHOLD_REQUEST = 23,
    CHECK_HEAD_OF_HOUSEHOLD_RESPONSE = 24,
    FIND_ID_REQUEST = 25,
    FIND_ID_RESPONSE = 26,
    APPROVAL_REQUEST = 27,
    APPROVAL_RESPONSE = 28,
    WALL_PAD_REQUEST = 29,
    WALL_PAD_RESPONSE = 30,
    SWITCH_START_REQUEST = 31,
    SWITCH_START_RESPONSE = 32,
    SWITCH_END_REQUEST = 33,
    SWITCH_END_RESPONSE = 34,
    USER_INFO_REQUEST = 35,
    USER_INFO_RESPONSE = 36,
    USER_EDIT_REQUEST = 37,
    USER_EDIT_RESPONSE = 38,
    USER_DELETE_REQUEST = 39,
    USER_DELETE_RESPONSE = 40,
    PASSWORD_REQUEST = 41,
    PASSWORD_RESPONSE = 42,
    FIND_PASSWORD_REQUEST = 43,
    FIND_PASSWORD_RESPONSE = 44,
    REGISTER_NOTIFICATION = 45,
    USER_DELETE_NOTIFICATION = 46,
    APPROVAL_DELETE_REQUEST = 47,
    APPROVAL_DELETE_RESPONSE = 48,
    HEAD_OF_HOUSEHOLD_NOTIFICATION = 39,
    FIND_PASSWORD_INFO_REQUEST = 50,
    FIND_PASSWORD_INFO_RESPONSE = 51,
    FIND_NEW_PASSWORD_REQUEST = 52,
    FIND_NEW_PASSWORD_RESPONSE = 53
    
}

export enum GuardSubTypes {

    GUARD_STATE_REQUEST = 1,
    GUARD_STATE_RESPONSE = 2,
    GUARD_NOTIFY = 3,
    EMERGENCY_LIST_REQUEST = 4,
    EMERGENCY_LIST_RESPONSE = 5,
    SECURITY_ACT_REQUEST = 6,
    SECURITY_ACT_RESPONSE = 7,
    SECURITY_QUERY_REQUEST = 8,
    SECURITY_QUERY_RESPONSE = 9,
    SECURITY_SET_REQUEST = 10,
    SECURITY_SET_RESPONSE = 11,
    SECURITY_PASSWORD_SET_REQUEST = 12,
    SECURITY_PASSWORD_SET_RESPONSE = 13,
    SECURITY_SET_NOTIFICATION = 14,
    SECURITY_INVASION_NOTIFICATION = 15,
    SECURITY_INVASION_NOT_RELEASED_NOTIFICATION = 16,
    SECURITY_PASSWORD_NOTIFICATION = 17,
    SECURITY_RELEASE_NOTIFICATION = 18

}

export enum DeviceSubTypes {

    QUERY_REQUEST = 1,
    QUERY_RESPONSE = 2,
    INVOKE_REQUEST = 3,
    INVOKE_RESPONSE = 4,
    INVOKE_NOTIFICATION = 5,
    WALL_SOCKET_QUERY_REQUEST = 6,
    WALL_SOCKET_QUERY_RESPONSE = 7,
    WALL_SOCKET_INVOKE_REQUEST = 8,
    WALL_SOCKET_INVOKE_RESPONSE = 9
    
}

export enum EMSSubTypes {
    // TODO: These types are not necessary on HomeBridge
}

export enum InfoSubTypes {
    // TODO: These types are not necessary on HomeBridge
}

export enum HealthcareSubTypes {
    // TODO: These types are not necessary on HomeBridge
}

export enum SettingSubTypes {
    PUSH_QUERY_REQUEST = 1,
    PUSH_QUERY_RESPONSE = 2,
    PUSH_SETTING_REQUEST = 3,
    PUSH_SETTING_RESPONSE = 4,
    USER_LIST_REQUEST = 5,
    USER_LIST_RESPONSE = 6,
    USER_DELETE_REQUEST = 7,
    USER_DELETE_RESPONSE = 8,
    USER_DELETE_NOTIFICATION = 9,
    COMMUNAL_ENTRANCE_PASSWORD_QUERY_REQUEST = 10,
    COMMUNAL_ENTRANCE_PASSWORD_QUERY_RESPONSE = 11,
    COMMUNAL_ENTRANCE_PASSWORD_INVOKE_REQUEST = 12,
    COMMUNAL_ENTRANCE_PASSWORD_INVOKE_RESPONSE = 13,
    COMMUNAL_ENTRANCE_PASSWORD_NOTIFICATION = 14,
    LONG_TERM_UNUSED_QUERY_REQUEST = 15,
    LONG_TERM_UNUSED_QUERY_RESPONSE = 16,
    LONG_TERM_UNUSED_INVOKE_REQUEST = 17,
    LONG_TERM_UNUSED_INVOKE_RESPONSE = 18,
    VISITOR_LIGHT_ALARM_QUERY_REQUEST = 19,
    VISITOR_LIGHT_ALARM_QUERY_RESPONSE = 20,
    VISITOR_LIGHT_ALARM_UPDATE_REQUEST = 21,
    VISITOR_LIGHT_ALARM_UPDATE_RESPONSE = 22,
    LONG_TERM_UNUSED_NOTIFICATION = 23,
    CUSTOMIZATION_LIST_REQUEST = 24,
    CUSTOMIZATION_LIST_RESPONSE = 25,
    CUSTOMIZATION_GET_REQUEST = 26,
    CUSTOMIZATION_GET_RESPONSE = 27,
    CUSTOMIZATION_SET_REQUEST = 28,
    CUSTOMIZATION_SET_RESPONSE = 29,
    CUSTOMIZATION_DELETE_REQUEST = 30,
    CUSTOMIZATION_DELETE_RESPONSE = 31,
    CUSTOMIZATION_NOTIFICATION = 32
}

// TODO: HomeKit currently does not support one-way requests like calling elevator
export enum ElevatorCallSubTypes {

    CALL_REQUEST = 1,
    CALL_RESPONSE = 2,
    ARRIVE_NOTIFICATION = 3

}

export enum EtceteraSubTypes {
    // TODO: These types are not necessary on HomeBridge
}

export enum ApplicationLogSubTypes {

    WEATHER_REQUEST = 1,
    LIVING_REQUEST = 2,
    MAIN_MENU_REQUEST = 3,
    SMART_ELECTRONICS_REQUEST = 4,
    EMS_ELECTRONICS_REQUEST = 5,
    EMS_GAS_REQUEST = 6,
    EMS_WATER_REQUEST = 7,
    EMS_HOTWATER_REQUEST = 8,
    EMS_HEATING_REQUEST = 9

}

export type PushSubTypes = DevicePushTypes | EventPushTypes;

export enum PushTypes {
    DEVICES = 3,
    EVENTS = 5
}

export enum DevicePushTypes {
    LIGHT_CHANGES = 5
}

export enum EventPushTypes {
    CAR_GETTING_IN = 46,
    FRONT_DOOR_CHANGES = 61
}