name: Fetch Complex Info (Smart eLife)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Packages
        run: npm ci --ignore-scripts

      - name: Audit Packages
        run: npm audit --audit-level=high

      - name: Verify Package Signatures
        run: npm audit signatures

      - name: Run Cronjob
        run: npm run refresh-smart-elife

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            complexes/smart-elife/*.json
          commit-message: '[Scheduled] Update Smart eLife complexes'
          branch: fetch-complex-smart-elife-patch
          title: '[Scheduled] Update Smart eLife complexes'
          body: |
            Complex info (Smart eLife) have been changed
            
            This is automatically generated Pull Request
          reviewers: OrigamiDream
