name: Publish beta packages on npm.js

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: Name of the branch where the workflow to be executed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: fregante/setup-git-user@v1

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci

      - name: Update the package version in beta stage
        run: npm version prerelease --preid=beta

      - name: Push changes to the repo
        run: git push origin "${{ github.event.inputs.branch }}"

      - name: Publish on npm.js
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
